// Default chart type per inference test (QuickView auto-selection)
export const CHART_FOR_TEST = {
  t_welch: 'violin',
  t_paired: 'violin',
  t_one: 'histogram',
  trimmed: 'violin',
  z_known: 'histogram',
  sign: 'violin',
  mwu: 'violin',
  wilcoxon: 'violin',

  anova: 'barci',
  welch_anova: 'barci',
  twoway: 'barci',
  ancova: 'barci',
  rm_anova: 'barci',
  kruskal: 'barci',
  friedman: 'barci',
  cochranQ: 'barci',

  pearson: 'scatterfit',
  spearman: 'scatter',
  kendall: 'scatter',
  partial: 'scatterfit',
  pointbis: 'scatterfit',
  ols_simple: 'scatterfit',
  ols_multi: 'scatterfit',
  polynomial: 'scatterfit',
  hierarchical: 'scatterfit',
  logistic: 'scatterfit',
  mediation: 'path',
  med_bootstrap: 'histogram',
  moderation: 'scatterfit',

  chisq: 'mosaic',
  chigof: 'histogram',
  fisher: 'mosaic',
  mcnemar: 'mosaic',
  binomial: 'histogram',
  prop1: 'histogram',
  prop2: 'barci',

  pca: 'scree',
  efa: 'loading',
  cronbach: 'barci',
  splithalf: 'barci',
  icc: 'barci',
  kappa: 'mosaic',

  meta: 'forest',
  did: 'scatter',

  normality: 'qq',
  homogeneity: 'barci',
  bootstrap: 'histogram',
  samplesize: 'power',
  grubbs: 'histogram',
};
