import { C } from '../palette.js';

export const TREE = [
  {
    cat: "COMPARE MEANS", color: C.pos,
    tests: [
      { id: "t_welch",   label: "Welch t-test",         tag: "2 groups · d · power · 95% CI" },
      { id: "t_one",     label: "One-sample t-test",     tag: "vs null mean · Cohen's d" },
      { id: "t_paired",  label: "Paired t-test",         tag: "matched · repeated measures" },
      { id: "trimmed",   label: "Yuen's Trimmed t-test", tag: "robust · outlier-resistant · 20% trim" },
      { id: "z_known",   label: "z-test (known σ)",      tag: "population SD known" },
      { id: "sign",      label: "Sign Test",             tag: "minimal assumptions · fast" },
    ],
  },
  {
    cat: "ANALYSIS OF VARIANCE", color: "#60a5fa",
    tests: [
      { id: "anova",       label: "One-Way ANOVA",    tag: "3+ groups · Tukey HSD · η² · ω²" },
      { id: "welch_anova", label: "Welch's ANOVA",    tag: "robust to unequal variances" },
      { id: "twoway",      label: "Two-Way ANOVA",    tag: "2 factors · interaction · cell means" },
      { id: "ancova",      label: "ANCOVA",           tag: "covariate-adjusted group means" },
      { id: "rm_anova",    label: "RM ANOVA",         tag: "repeated measures · Greenhouse-Geisser ε" },
      { id: "kruskal",     label: "Kruskal-Wallis",   tag: "nonparametric ANOVA · η²" },
      { id: "friedman",    label: "Friedman Test",    tag: "nonparametric RM · Kendall's W" },
      { id: "cochranQ",    label: "Cochran's Q",      tag: "k related binary proportions" },
    ],
  },
  {
    cat: "NONPARAMETRIC", color: C.warn,
    tests: [
      { id: "mwu",      label: "Mann-Whitney U",        tag: "2 groups · rank-biserial r · Cliff's δ" },
      { id: "wilcoxon", label: "Wilcoxon Signed-Rank",  tag: "paired / one-sample · r" },
    ],
  },
  {
    cat: "CORRELATION", color: C.accent,
    tests: [
      { id: "pearson",   label: "Pearson r",          tag: "linear · 95% CI (Fisher z) · R²" },
      { id: "spearman",  label: "Spearman ρ",         tag: "rank-based · monotonic" },
      { id: "kendall",   label: "Kendall τ-b",        tag: "concordant pairs · small n" },
      { id: "partial",   label: "Partial Correlation", tag: "control for Z · semi-partial r" },
      { id: "pointbis",  label: "Point-Biserial r",   tag: "binary + continuous" },
    ],
  },
  {
    cat: "REGRESSION", color: "#ff6bd6",
    tests: [
      { id: "ols_simple",    label: "Simple OLS",             tag: "β · SE · t · R² · Durbin-Watson" },
      { id: "ols_multi",     label: "Multiple OLS",           tag: "β + VIF + adj. R² + collinearity" },
      { id: "polynomial",    label: "Polynomial Regression",  tag: "quadratic / cubic / quartic trends" },
      { id: "hierarchical",  label: "Hierarchical Regression", tag: "model comparison · ΔR² · F-change" },
      { id: "logistic",      label: "Logistic Regression",    tag: "binary · OR · AIC · BIC · F1" },
      { id: "ordinal",       label: "Ordinal Logistic",       tag: "proportional odds · OR · Likert" },
      { id: "poisson",       label: "Poisson Regression",      tag: "IRR · deviance · dispersion" },
      { id: "negbinom",      label: "Negative Binomial",       tag: "count · overdispersion · AIC" },
      { id: "mediation",     label: "Mediation",              tag: "Baron-Kenny + Sobel + path diagram" },
      { id: "med_bootstrap", label: "Bootstrap Mediation",    tag: "percentile CI for indirect effect" },
      { id: "moderation",    label: "Moderation",             tag: "X×Z interaction · simple slopes" },
    ],
  },
  {
    cat: "CATEGORICAL", color: C.purple,
    tests: [
      { id: "chisq",    label: "Chi-Square",         tag: "independence · Cramér's V · observed vs expected" },
      { id: "chigof",   label: "Chi-Square GoF",     tag: "goodness-of-fit · Cohen's w" },
      { id: "fisher",   label: "Fisher's Exact",     tag: "small n · exact · 2×2 · OR" },
      { id: "mcnemar",  label: "McNemar's Test",     tag: "paired proportions · before/after" },
      { id: "binomial", label: "Binomial Exact",     tag: "exact · small n · p̂ vs p₀" },
      { id: "prop1",    label: "One-Proportion z",   tag: "p̂ vs p₀ · Cohen's h · CI" },
      { id: "prop2",    label: "Two-Proportion z",   tag: "RR · OR · ARR · NNT" },
    ],
  },
  {
    cat: "EQUIVALENCE & BAYES", color: C.ok,
    tests: [
      { id: "tost",    label: "TOST Equivalence",    tag: "two one-sided t-tests · bounds" },
      { id: "bayes_t", label: "Bayesian t-test",     tag: "BF₁₀ · JZS Cauchy prior · Bayes factors" },
      { id: "bayes_r", label: "Bayesian Correlation", tag: "BF for H₀: ρ = 0" },
    ],
  },
  {
    cat: "MULTIVARIATE", color: "#34d399",
    tests: [
      { id: "pca",       label: "PCA",               tag: "eigenvalues · loadings · scree · scores" },
      { id: "efa",       label: "EFA (Varimax)",      tag: "factor analysis · communalities · uniqueness" },
      { id: "manova",    label: "MANOVA",            tag: "Wilks Λ · Pillai · Roy · Hotelling" },
      { id: "cancorr",   label: "Canonical Correlation", tag: "Rc · loadings · χ²" },
      { id: "lda",       label: "Linear Discriminant", tag: "LDA · accuracy · coefficients" },
      { id: "mds_classical", label: "Classical MDS",   tag: "metric MDS · stress · 2D embedding" },
      { id: "mds_sammon",    label: "Sammon Mapping",  tag: "nonlinear MDS · local-distance weighting" },
      { id: "mds_nonmetric", label: "Non-Metric MDS",  tag: "Kruskal · rank-order MDS" },
      { id: "cronbach",  label: "Cronbach's α",       tag: "internal consistency · α-if-deleted · item-total r" },
      { id: "splithalf", label: "Split-Half",         tag: "Spearman-Brown corrected reliability" },
      { id: "icc",       label: "ICC(2,1)",           tag: "inter-rater reliability · two-way random" },
      { id: "kappa",     label: "Cohen's κ",          tag: "categorical agreement · weighted" },
    ],
  },
  {
    cat: "PSYCHOMETRICS", color: "#f472b6",
    tests: [
      { id: "omega",       label: "McDonald's ω",        tag: "total + hierarchical · factor model" },
      { id: "parallel",    label: "Parallel Analysis",   tag: "Monte Carlo scree · factor retention" },
      { id: "irt_1pl",     label: "IRT Rasch (1PL)",      tag: "difficulty · θ · ICC" },
      { id: "irt_2pl",     label: "IRT 2PL",             tag: "a · b · ICC curves" },
      { id: "scale_score", label: "Scale Scoring",       tag: "sum/mean · reverse · subscale" },
    ],
  },
  {
    cat: "MULTILEVEL MODELS", color: "#2dd4bf",
    tests: [
      { id: "hlm_ri", label: "Random Intercept",  tag: "two-level · variance comps · ICC" },
      { id: "hlm_rs", label: "Random Slope",      tag: "growth · slope variance" },
      { id: "icc_ml", label: "Multilevel ICC",     tag: "between var · design effect" },
    ],
  },
  {
    cat: "CLUSTERING", color: "#fb923c",
    tests: [
      { id: "kmeans", label: "k-Means",            tag: "k=2..8 · silhouette" },
      { id: "hclust", label: "Hierarchical Cluster", tag: "Ward · linkage dendrogram height" },
      { id: "lca",    label: "Latent Class Analysis", tag: "2–4 classes · EM · BIC" },
    ],
  },
  {
    cat: "NETWORK", color: "#a78bfa",
    tests: [
      { id: "centrality", label: "Centrality Measures", tag: "degree · between · eigen · closeness" },
      { id: "community",  label: "Community Detection", tag: "modularity · greedy" },
      { id: "sociogram",  label: "Sociogram",           tag: "force layout · adjacency" },
    ],
  },
  {
    cat: "META-ANALYSIS & CAUSAL", color: "#fbbf24",
    tests: [
      { id: "meta", label: "Random-Effects Meta", tag: "DerSimonian-Laird · I² · τ · prediction interval" },
      { id: "did",  label: "Diff-in-Differences", tag: "causal inference · policy evaluation" },
      { id: "psm",   label: "Propensity Score Match", tag: "logistic PS · ATT · balance" },
      { id: "iv2sls",label: "IV / 2SLS",           tag: "instrument · first-stage F" },
      { id: "its",   label: "Interrupted Time Series", tag: "segmented regression" },
      { id: "rdd",   label: "Regression Discontinuity", tag: "local linear · bandwidth" },
    ],
  },
  { cat: "DIAGNOSTICS", color: '#38bdf8',
    tests: [
      { id: "normality",   label: "Normality Tests",              tag: "Shapiro-Wilk · D'Agostino-Pearson" },
      { id: "homogeneity", label: "Homogeneity Tests",            tag: "Levene · Bartlett · variance equality" },
      { id: "grubbs",      label: "Grubbs' Test",                 tag: "single outlier detection · α" },
      { id: "sensitivity", label: "Sensitivity Analysis (LOO)",   tag: "leave-one-out · influence" },
      { id: "effectconv",  label: "Effect Size Conversion",       tag: "d ↔ r ↔ η² · Cohen's conventions" },
      { id: "corrections", label: "Multiple Comparisons",         tag: "Bonferroni · Holm · Benjamini-Hochberg" },
      { id: "samplesize",  label: "Sample Size Calculator",       tag: "power · d · r · α required N" },
    ],
  },
  { cat: "ROBUST STATISTICS", color: '#fb923c',
    tests: [
      { id: "theil_sen",        label: "Theil-Sen Slope",          tag: "median pairwise · nonparametric" },
      { id: "mm_estimator",     label: "MM-Estimator",             tag: "high breakdown · S/M iterative" },
      { id: "mad_scale",        label: "MAD Scale",                tag: "median absolute deviation · robust σ" },
      { id: "hampel_m",         label: "Hampel M-Estimator",       tag: "redescending psi · location" },
      { id: "mcd_cov",          label: "MCD Covariance",           tag: "minimum covariance determinant · robust Σ" },
      { id: "s_estimator",      label: "S-Estimator",              tag: "bisquare rho · high bdp" },
      { id: "lts_reg",          label: "LTS Regression",           tag: "least trimmed squares · robust OLS" },
      { id: "qq_band",          label: "QQ Confidence Bands",      tag: "simulated envelope · normality check" },
    ],
  },
  { cat: "BAYESIAN MODELING", color: '#a78bfa',
    tests: [
      { id: "bic_bf",          label: "BIC Bayes Factor",           tag: "model comparison · Schwartz approx" },
      { id: "beta_binom_post", label: "Beta-Binomial Posterior",    tag: "conjugate update · proportion" },
      { id: "gamma_pois_post", label: "Gamma-Poisson Posterior",    tag: "count data · conjugate" },
      { id: "norm_norm_post",  label: "Normal-Normal Posterior",    tag: "known σ · conjugate μ" },
      { id: "nig_post",        label: "NIG Posterior",              tag: "Normal-Inverse-Gamma · regression" },
      { id: "bayes_linreg",    label: "Bayesian Linear Reg",        tag: "conjugate/MCMC · coeff posterior" },
      { id: "bayes_logit",     label: "Bayesian Logistic Reg",      tag: "MCMC · binary outcome" },
      { id: "bayes_pois",      label: "Bayesian Poisson Reg",       tag: "MCMC · count outcome" },
      { id: "bayes_dic",       label: "Bayesian DIC",               tag: "deviance · information criterion" },
      { id: "bma_reg",         label: "BMA Regression",             tag: "model averaging · BIC weights" },
    ],
  },
  { cat: "MISSING DATA", color: '#fbbf24',
    tests: [
      { id: "little_mcar",   label: "Little's MCAR Test",   tag: "missing completely at random · χ²" },
      { id: "mice_imp",      label: "MICE Imputation",       tag: "multiple imputation · chained equations" },
      { id: "rubin_pool",    label: "Rubin's Rules",         tag: "pooled estimates · between/within variance" },
      { id: "fmi",           label: "Fraction Missing Info", tag: "λ · proportion of missing information" },
      { id: "em_impute",     label: "EM Imputation",         tag: "expectation-maximization · MVN" },
      { id: "miss_patt",     label: "Missingness Pattern",   tag: "visual map · . = present X = missing" },
      { id: "complete_cases",label: "Complete Cases",        tag: "listwise deletion · complete rows" },
    ],
  },
  { cat: "POWER ANALYSIS", color: '#f472b6',
    tests: [
      { id: "pow_anova",   label: "ANOVA Power",            tag: "Cohen's f · n per group" },
      { id: "pow_chi",     label: "Chi-Square Power",       tag: "Cohen's w · df" },
      { id: "pow_logit",   label: "Logistic Power",         tag: "OR · event rate approx" },
      { id: "pow_mixed",   label: "Mixed Models Power",      tag: "ICC · design effect" },
      { id: "pow_med",     label: "Mediation Power",        tag: "Monte Carlo · ab paths" },
      { id: "bootstrap",   label: "Bootstrap CI",            tag: "mean · median · SD · B=1999" },
    ],
  },
  { cat: "POWER & SAMPLE SIZE (EXTENDED)", color: '#f9a8d4',
    tests: [
      { id: "pow_cox",       label: "Cox PH Power",              tag: "hazard ratio · n events" },
      { id: "pow_meta",      label: "Meta-Analysis Power",       tag: "k studies · pooled d" },
      { id: "pow_equiv",     label: "Equivalence Power (TOST)",  tag: "mean diff · bounds" },
      { id: "pow_intanova",  label: "Interaction ANOVA Power",   tag: "2-way · Cohen's f" },
      { id: "pow_corr",      label: "Correlation Power",         tag: "n · r" },
      { id: "pow_ttest",     label: "T-Test Power",              tag: "n1/n2 · Cohen's d" },
      { id: "pow_oneprop",   label: "One-Proportion Power",      tag: "n · p0 vs p1" },
      { id: "pow_twoprop",   label: "Two-Proportion Power",      tag: "n1/n2 · p1 vs p2" },
      { id: "pow_wilcoxon",  label: "Wilcoxon Power",            tag: "n1/n2 · Cohen's d" },
      { id: "pow_logrank",   label: "Log-Rank Power",            tag: "survival · hazard ratio" },
      { id: "pow_rmanova",   label: "RM ANOVA Power",            tag: "k occasions · GG ε" },
      { id: "pow_olsapa",    label: "OLS Power",                 tag: "R² · k predictors" },
      { id: "pow_spearman",  label: "Spearman Power",            tag: "n · ρ" },
      { id: "reqn_t",        label: "Required N (t-test)",       tag: "Cohen's d → n/group" },
      { id: "reqn_corr",     label: "Required N (Correlation)",  tag: "r → N" },
      { id: "reqn_oneprop",  label: "Required N (One Proportion)", tag: "p0/p1 → N" },
      { id: "reqn_twoprop",  label: "Required N (Two Proportions)", tag: "p1/p2 → n/group" },
      { id: "reqn_wilcoxon", label: "Required N (Wilcoxon)",     tag: "Cohen's d → n" },
      { id: "reqn_logrank",  label: "Required N (Log-Rank)",     tag: "hazard ratio → events" },
      { id: "reqn_ols",      label: "Required N (OLS)",          tag: "R² → N" },
      { id: "reqn_anova",    label: "Required N (ANOVA)",        tag: "Cohen's f → n/group" },
    ],
  },
  { cat: "AGENT-BASED MODELS", color: '#a78bfa',
    tests: [
      { id: "abm_morani",     label: "Spatial Moran's I",           tag: "spatial autocorrelation · agents" },
      { id: "abm_conv",       label: "Simulation Convergence",      tag: "window-averaged · tolerance Δ" },
      { id: "abm_sobol",      label: "Sobol Sensitivity (ABM)",     tag: "input-output variance decomposition" },
      { id: "abm_summary",    label: "Agent Summary",               tag: "mean · sd · min · max per field" },
      { id: "abm_scenario",   label: "Scenario Comparison",         tag: "multi-run summary stats" },
      { id: "abm_threshold",  label: "Threshold Model",             tag: "binary cascade · activation" },
      { id: "abm_diffusion",  label: "Network Diffusion",           tag: "SIR-like · adjacency spread" },
      { id: "abm_segregation",label: "Segregation Index",           tag: "dissimilarity · exposure" },
    ],
  },
  { cat: "MULTI-ARMED BANDITS", color: '#60a5fa',
    tests: [
      { id: "bandit_eps",      label: "Epsilon-Greedy",        tag: "ε-exploration · regret" },
      { id: "bandit_ucb",      label: "UCB",                   tag: "upper confidence bound · Hoeffding" },
      { id: "bandit_thompson", label: "Thompson Sampling",     tag: "Bayesian posterior · Beta-Bernoulli" },
      { id: "bandit_context",  label: "Contextual Bandit",     tag: "LinUCB · features" },
      { id: "bandit_pg",       label: "Policy Gradient",       tag: "REINFORCE · score function" },
      { id: "bandit_softmax",  label: "Softmax Selection",     tag: "Boltzmann · temperature τ" },
      { id: "bandit_ql",       label: "Q-Learning",            tag: "tabular · TD-ε" },
      { id: "bandit_sarsa",    label: "SARSA",                 tag: "on-policy TD · ε-greedy" },
      { id: "bandit_dqn",      label: "Deep Q-Network",        tag: "neural Q-approx · experience replay" },
    ],
  },
  { cat: "RECORD LINKAGE", color: '#34d399',
    tests: [
      { id: "link_jaro",   label: "Jaro-Winkler",               tag: "string similarity · typo-tolerant" },
      { id: "link_lev",    label: "Levenshtein Distance",       tag: "edit distance · dynamic programming" },
      { id: "link_fel",    label: "Fellegi-Sunter",             tag: "probabilistic linkage · EM weights" },
      { id: "link_block",  label: "Record Blocking",            tag: "coarse partition · blocking key" },
      { id: "link_thresh", label: "Match Threshold",            tag: "precision-recall · F-score" },
      { id: "link_prob",   label: "Probabilistic Linkage",       tag: "weights · match probability" },
      { id: "link_dedup",  label: "Deduplication",              tag: "duplicate detection · grouping" },
    ],
  },
  { cat: "PRIVACY", color: '#fbbf24',
    tests: [
      { id: "priv_laplace",    label: "Laplace Mechanism",      tag: "ε-DP · additive noise" },
      { id: "priv_synthetic",  label: "Synthetic Data",         tag: "bootstrap · resampled copies" },
      { id: "priv_kanon",      label: "K-Anonymity",            tag: "quasi-identifier grouping" },
      { id: "priv_diff",       label: "Differential Privacy",    tag: "(ε,δ)-DP · query sensitivity" },
      { id: "priv_mask",       label: "Data Masking",            tag: "suppression · perturbation" },
      { id: "priv_ldiv",       label: "l-Diversity",            tag: "sensitive attribute entropy" },
      { id: "priv_tclose",     label: "t-Closeness",            tag: "EMD distance · distribution" },
    ],
  },
  { cat: "PATIENT-REPORTED OUTCOMES", color: '#ff6bd6',
    tests: [
      { id: "pro_rci",       label: "Reliable Change Index",     tag: "individual trajectory · Sdiff" },
      { id: "pro_mid",       label: "Minimal Important Diff",    tag: "anchor-based · ROC threshold" },
      { id: "pro_responder", label: "Responder Analysis",        tag: "threshold · before/after" },
      { id: "pro_eq5d",      label: "EQ-5D Index",               tag: "health utility · 5 domains" },
      { id: "pro_srm",       label: "Standardized Response Mean", tag: "change / SD_change" },
      { id: "pro_ctgov",     label: "Clinical Trials Gov",       tag: "primary · secondary · NCT" },
      { id: "pro_consort",   label: "CONSORT Checklist",         tag: "compliance · item count" },
    ],
  },
  { cat: "RISK-ADJUSTED MONITORING", color: '#fb923c',
    tests: [
      { id: "ram_cusum",   label: "RA-CUSUM",             tag: "cumulative sum · risk-adjusted" },
      { id: "ram_vlad",    label: "VLAD",                  tag: "variable life-adjusted display" },
      { id: "ram_sprt",    label: "RA-SPRT",               tag: "sequential probability ratio test" },
      { id: "ram_funnel",  label: "Funnel Plot",           tag: "precision · control limits" },
      { id: "ram_cchart",  label: "C-Chart",               tag: "Poisson count · risk-adjusted" },
      { id: "ram_safety",  label: "Safety Signal",         tag: "E / O · disproportionality" },
      { id: "ram_prr",     label: "PRR Analysis",          tag: "proportional reporting ratio" },
    ],
  },
  { cat: "RECOMMENDATION", color: '#2dd4bf',
    tests: [
      { id: "rec_cf",   label: "Collaborative Filter",  tag: "user-item · neighbor similarity" },
      { id: "rec_mf",   label: "Matrix Factorization",  tag: "SVD · latent factors" },
      { id: "rec_topn", label: "Top-N Recommender",     tag: "precision@k · recall@k" },
    ],
  },
  { cat: "SINGLE-CASE DESIGNS", color: '#f472b6',
    tests: [
      { id: "sced_tauu",  label: "Tau-U",                      tag: "non-overlap · trend-corrected" },
      { id: "sced_pnd",   label: "PND",                        tag: "percentage non-overlapping data" },
      { id: "sced_pem",   label: "PEM",                        tag: "percentage exceeding median" },
      { id: "sced_nap",   label: "NAP",                        tag: "non-overlap of all pairs" },
      { id: "sced_rand",  label: "Randomization Test",         tag: "SCED · permutation test" },
      { id: "sced_bctau", label: "Baseline-Corrected Tau",     tag: "adjusted overlap · baseline trend" },
      { id: "sced_bcsmd", label: "Between-Case SMD",           tag: "between-case standardized mean difference" },
    ],
  },
  { cat: "SENSITIVITY ANALYSIS", color: '#fb7185',
    tests: [
      { id: "sens_morris",    label: "Morris Method",          tag: "elementary effects · screening" },
      { id: "sens_fast",      label: "FAST Sensitivity",       tag: "Fourier amplitude · main effects" },
      { id: "sens_modelcomp", label: "Model Comparison",       tag: "AIC · BIC · likelihood ratio" },
      { id: "sens_forecast",  label: "Forecast Combination",   tag: "equal-weight ensemble · MSE" },
      { id: "sens_sobol1",    label: "Sobol First Order",      tag: "main effect index · Si" },
      { id: "sens_sobolt",    label: "Sobol Total Index",      tag: "total effect · STi" },
      { id: "sens_delta",     label: "Delta Method",           tag: "SE of transformed statistic" },
      { id: "sens_andrews",   label: "Andrews Plot",           tag: "Fourier function · multivariate visual" },
    ],
  },
  { cat: "BOOTSTRAP", color: '#818cf8',
    tests: [
      { id: "boot_ci",        label: "Bootstrap CI",           tag: "percentile · bias-corrected" },
      { id: "boot_se",        label: "Bootstrap SE",           tag: "standard error · resampling" },
      { id: "boot_test",      label: "Bootstrap Hypothesis",   tag: "null distribution · p-value" },
      { id: "boot_jack",      label: "Jackknife",              tag: "leave-one-out · bias estimate" },
      { id: "boot_tci",       label: "Bootstrap-t CI",         tag: "studentized · t pivot" },
      { id: "boot_influence", label: "Empirical Influence",    tag: "infinitesimal jackknife" },
      { id: "boot_mediation", label: "Bootstrap Mediation",    tag: "ab path · percentile CI" },
      { id: "boot_modmed",    label: "Moderated Mediation",    tag: "conditional indirect effect" },
      { id: "boot_splitconf", label: "Split Conformal",        tag: "prediction interval" },
      { id: "boot_confpval",  label: "Conformal P-Values",     tag: "distribution-free testing" },
      { id: "boot_jackplus",  label: "Jackknife+",             tag: "predictive inference" },
    ],
  },
  { cat: "SURVIVAL ANALYSIS", color: '#4ade80',
    tests: [
      { id: "km",      label: "Kaplan-Meier",  tag: "survival curve · median survival" },
      { id: "logrank", label: "Log-Rank Test", tag: "2-group survival comparison" },
      { id: "coxph",   label: "Cox PH",        tag: "hazard ratios · covariates" },
    ],
  },
  { cat: "TIME SERIES", color: '#38bdf8',
    tests: [
      { id: "adf",  label: "Augmented Dickey-Fuller", tag: "unit root · stationarity" },
      { id: "acf",  label: "Autocorrelation (ACF)",   tag: "lag correlation" },
      { id: "pacf", label: "Partial Autocorrelation (PACF)", tag: "lag correlation, controlled" },
    ],
  },
  { cat: "OUTLIER DETECTION", color: '#f87171',
    tests: [
      { id: "lof",     label: "Local Outlier Factor", tag: "density-based · k-neighbors" },
      { id: "iforest", label: "Isolation Forest",     tag: "tree-based anomaly score" },
    ],
  },
  { cat: "ECONOMETRICS", color: '#facc15',
    tests: [
      { id: "panel_fe",      label: "Panel Fixed Effects",  tag: "within-unit demeaning" },
      { id: "panel_re",      label: "Panel Random Effects", tag: "Swamy-Arora FGLS" },
      { id: "hausman_panel", label: "Hausman Test (FE vs RE)", tag: "specification test" },
    ],
  },
  { cat: "GENERALIZED ADDITIVE MODELS", color: '#22d3ee',
    tests: [
      { id: "gam_backfit",  label: "GAM Backfitting",  tag: "smooth predictors · R²" },
      { id: "gam_interact", label: "GAM Interaction",  tag: "tensor-product smooth" },
    ],
  },
  { cat: "MIXTURE MODELS", color: '#c084fc',
    tests: [
      { id: "gmm_cluster", label: "Gaussian Mixture Model",  tag: "EM · soft clustering" },
      { id: "lpa",         label: "Latent Profile Analysis", tag: "EM · continuous indicators" },
    ],
  },
  { cat: "DISTANCE & DEPENDENCE", color: '#5eead4',
    tests: [
      { id: "dist_corr", label: "Distance Correlation",  tag: "nonlinear association · Székely" },
      { id: "dist_cov",  label: "Distance Covariance",   tag: "nonlinear dependence" },
    ],
  },
  { cat: "SURVEY METHODOLOGY", color: '#fb7185',
    tests: [
      { id: "wmean",  label: "Weighted Descriptives",   tag: "weighted mean · SD · SE" },
      { id: "wcorr",  label: "Weighted Correlation",    tag: "weighted Pearson r" },
      { id: "deff",   label: "Design Effect",           tag: "DEFF · effective n · weight CV" },
      { id: "taylor", label: "Taylor Linearization",    tag: "stratified/clustered total · SE" },
    ],
  },
  { cat: "SEM", color: '#c4b5fd',
    tests: [
      { id: "sem", label: "Structural Equation Model", tag: "CFA · path model · fit indices" },
      { id: "ordinal_sem", label: "Ordinal SEM", tag: "polychoric correlations · Likert factor model" },
      { id: "path_analysis", label: "Path Analysis", tag: "direct · indirect · total effects" },
      { id: "latent_growth", label: "Latent Growth Model", tag: "intercept · slope · growth factors" },
      { id: "bifactor", label: "Bifactor Model", tag: "general + group factors · ω hierarchical" },
    ],
  },
];
