// Default chart type per inference test (QuickView auto-selection)
export const CHART_FOR_TEST = {
  t_welch: 'violin',
  t_paired: 'violin',
  t_one: 'histogram',
  trimmed: 'violin',
  z_known: 'histogram',
  sign: 'violin',

  mwu: 'violin',
  wilcoxon: 'violin',

  tost: 'violin',
  bayes_t: 'violin',
  bayes_r: 'scatterfit',

  anova: 'barci',
  welch_anova: 'barci',
  twoway: 'barci',
  ancova: 'barci',
  rm_anova: 'barci',
  kruskal: 'barci',
  friedman: 'barci',
  cochranQ: 'barci',

  pearson: 'scatterfit',
  spearman: 'scatter',
  kendall: 'scatter',
  partial: 'scatterfit',
  pointbis: 'scatterfit',
  ols_simple: 'scatterfit',
  ols_multi: 'scatterfit',
  polynomial: 'scatterfit',
  hierarchical: 'scatterfit',
  logistic: 'scatterfit',
  ordinal: 'scatterfit',
  poisson: 'scatterfit',
  negbinom: 'scatterfit',
  mediation: 'path',
  med_bootstrap: 'histogram',
  moderation: 'slopes',

  chisq: 'mosaic',
  chigof: 'histogram',
  fisher: 'mosaic',
  mcnemar: 'mosaic',
  binomial: 'histogram',
  prop1: 'histogram',
  prop2: 'barci',

  pca: 'scree',
  efa: 'loading',

  manova: 'scatterfit',
  cancorr: 'heatmap',
  lda: 'scatterfit',

  cronbach: 'barci',
  splithalf: 'barci',
  icc: 'barci',
  kappa: 'mosaic',

  omega: 'barci',
  parallel: 'scree',
  irt_1pl: 'irtplot',
  irt_2pl: 'irtplot',
  scale_score: 'histogram',

  hlm_ri: 'caterpillar',
  hlm_rs: 'spaghetti',
  icc_ml: 'barci',

  kmeans: 'histogram',
  hclust: 'histogram',
  lca: 'lca',

  centrality: 'histogram',
  community: 'barci',
  sociogram: 'sociogram',

  meta: 'forest',
  did: 'scatter',
  psm: 'scatterfit',
  iv2sls: 'scatterfit',
  its: 'its',
  rdd: 'rddplot',

  normality: 'qq',
  homogeneity: 'barci',
  bootstrap: 'histogram',
  samplesize: 'power',
  grubbs: 'histogram',

  pow_anova: 'power',
  pow_chi: 'power',
  pow_logit: 'power',
  pow_mixed: 'power',
  pow_med: 'power',

  effectconv: 'histogram',
  corrections: 'histogram',
  sensitivity: 'barci',
};
