// @vitest-environment happy-dom
import React from 'react';
import { describe, test, expect } from 'vitest';
import { render } from '@testing-library/react';
import { InferenceConfig } from './InferenceConfig.jsx';

const mockDs = { numeric: ['x', 'y'], categorical: ['group'] };

const noop = () => {};
const mockState = {
  grpVar: '', setGrpVar: noop, tgtVar: '', setTgtVar: noop,
  g1: '', setG1: noop, g2: '', setG2: noop,
  xVar: '', setXVar: noop, yVar: '', setYVar: noop,
  zVar: '', setZVar: noop, mVar: '', setMVar: noop,
  cat1: '', setCat1: noop, cat2: '', setCat2: noop,
  mu0: '0', setMu0: noop, sigma: '', setSigma: noop,
  preds: [], setPreds: noop, scaleVars: [], setScaleVars: noop,
  rmCols: [], setRmCols: noop, polDeg: 2, setPolDeg: noop,
  tostL: '', setTostL: noop, tostH: '', setTostH: noop,
  bfPrior: '', setBfPrior: noop, ssType: 'II', setSsType: noop,
  ssPow: 0.8, setSsPow: noop, ssD: 0.5, setSsD: noop,
  ssR: 0, setSsR: noop, effFrom: 'd', setEffFrom: noop,
  effVal: 0.5, setEffVal: noop, corrMeth: 'pearson', setCorrMeth: noop,
  pairsInput: '', setPairsInput: noop, bsStat: 'mean', setBsStat: noop,
  bsSeed: '42', setBsSeed: noop, bsB: '1000', setBsB: noop,
  nFactors: 1, setNFactors: noop,
  fx_a: '', setFxa: noop, fx_b: '', setFxb: noop,
  fx_c: '', setFxc: noop, fx_d: '', setFxd: noop,
  p1x: '', setP1x: noop, p1n: '', setP1n: noop,
  p2x: '', setP2x: noop, p2n: '', setP2n: noop,
  binoK: '', setBinoK: noop, binoN: '', setBinoN: noop,
  binoP: '', setBinoP: noop,
  didPCStr: '', setDidPCStr: noop, didPOStr: '', setDidPOStr: noop,
  didPTStr: '', setDidPTStr: noop, didPTtStr: '', setDidPTtStr: noop,
  onRunBs: noop, bsRunning: false, onRunMedBs: noop, medBsRunning: false,
  powAnovaF: 0.25, setPowAnovaF: noop, powKgroups: 3, setPowKgroups: noop,
  powNperGrp: 20, setPowNperGrp: noop,
  powChiW: 0.3, setPowChiW: noop, powChiDf: 4, setPowChiDf: noop,
  powChiN: 100, setPowChiN: noop,
  powLogitOr: 2, setPowLogitOr: noop, powLogitP0: 0.3, setPowLogitP0: noop,
  powLogitN: 50, setPowLogitN: noop,
  powMixedIcc: 0.05, setPowMixedIcc: noop, powMixedM: 10, setPowMixedM: noop,
  powMixedJ: 15, setPowMixedJ: noop, powMixedD: 0.5, setPowMixedD: noop,
  powMedA: 0.3, setPowMedA: noop, powMedB: 0.4, setPowMedB: noop,
  powMedSea: 0.1, setPowMedSea: noop, powMedSeb: 0.1, setPowMedSeb: noop,
  clusterK: 3, setClusterK: noop, linkage: 'ward', setLinkage: noop,
  nLcaClasses: 3, setNLcaClasses: noop,
  level2Var: '', setLevel2Var: noop, treatVar: '', setTreatVar: noop,
  edgeList: '', setEdgeList: noop,
  itsTimeStr: '', setItsTimeStr: noop, itsValStr: '', setItsValStr: noop,
  itsCut: '', setItsCut: noop,
  rddCutoff: '', setRddCutoff: noop, rddBw: '', setRddBw: noop,
  ivInstrument: '', setIvInstrument: noop,
  scaleMethod: 'sum', setScaleMethod: noop, reverseItems: [], setReverseItems: noop,
  // survival
  survTimeVar: '', setSurvTimeVar: noop, survEventVar: '', setSurvEventVar: noop,
  survStrataVar: '', setSurvStrataVar: noop, survPreds: [], setSurvPreds: noop,
  survDist: 'weibull', setSurvDist: noop, survClusterVar: '', setSurvClusterVar: noop,
  survCauseVar: '', setSurvCauseVar: noop, survIdVar: '', setSurvIdVar: noop,
  survStartVar: '', setSurvStartVar: noop, survStopVar: '', setSurvStopVar: noop,
  survTruncTime: '', setSurvTruncTime: noop, rsfNTrees: '50', setRsfNTrees: noop,
  survStates: '1,2,3', setSurvStates: noop, allCols: [],
  // time series
  tsValueVar: '', setTsValueVar: noop, tsP: '1', setTsP: noop,
  tsD: '0', setTsD: noop, tsQ: '1', setTsQ: noop,
  tsMaxP: '5', setTsMaxP: noop, tsMaxD: '2', setTsMaxD: noop, tsMaxQ: '5', setTsMaxQ: noop,
  tsPeriod: '4', setTsPeriod: noop, tsHorizon: '10', setTsHorizon: noop,
  tsBreakPoint: '', setTsBreakPoint: noop,
  tsCauseVar: '', setTsCauseVar: noop, tsEffectVar: '', setTsEffectVar: noop,
  tsMaxLag: '4', setTsMaxLag: noop, tsNRegimes: '2', setTsNRegimes: noop,
  tsDetType: 'const', setTsDetType: noop, tsMultiVars: [], setTsMultiVars: noop,
  tsGarchP: '1', setTsGarchP: noop, tsGarchQ: '1', setTsGarchQ: noop,
  tsMaxBreaks: '3', setTsMaxBreaks: noop,
  // finance
  finRfRate: '0', setFinRfRate: noop, finSpot: '100', setFinSpot: noop,
  finStrike: '100', setFinStrike: noop, finOptTime: '1', setFinOptTime: noop,
  finOptRate: '0.05', setFinOptRate: noop, finOptSigma: '0.2', setFinOptSigma: noop,
  finOptType: 'call', setFinOptType: noop, finMktPrice: '10', setFinMktPrice: noop,
  finOptSteps: '100', setFinOptSteps: noop, finNSim: '1000', setFinNSim: noop,
  finVaRAlpha: '0.05', setFinVaRAlpha: noop,
  finMarketVar: '', setFinMarketVar: noop, finSmbVar: '', setFinSmbVar: noop,
  finHmlVar: '', setFinHmlVar: noop, finMomVar: '', setFinMomVar: noop,
  // clinical
  clinMethodAVar: '', setClinMethodAVar: noop, clinMethodBVar: '', setClinMethodBVar: noop,
  clinRater1Var: '', setClinRater1Var: noop, clinRater2Var: '', setClinRater2Var: noop,
  clinRaters: [], setClinRaters: noop, clinWeight: 'linear', setClinWeight: noop,
  clinTp: '30', setClinTp: noop, clinFp: '10', setClinFp: noop,
  clinTn: '50', setClinTn: noop, clinFn: '10', setClinFn: noop,
  clinOutcomeVar: '', setClinOutcomeVar: noop, clinPredVar: '', setClinPredVar: noop,
  clinNGroups: '10', setClinNGroups: noop, clinStages: '3', setClinStages: noop,
  clinPvals: '', setClinPvals: noop, clinRiskThresholds: '', setClinRiskThresholds: noop,
  clinPrev: '0.2', setClinPrev: noop, clinOr: '2.0', setClinOr: noop,
  nriPoldStr: '', setNriPoldStr: noop, nriPnewStr: '', setNriPnewStr: noop,
  nriYtrueStr: '', setNriYtrueStr: noop,
  // dose-response
  drDoseVar: '', setDrDoseVar: noop, drRespVar: '', setDrRespVar: noop,
  drFcThresh: '1', setDrFcThresh: noop, drPThresh: '0.05', setDrPThresh: noop,
  drTrtVar: '', setDrTrtVar: noop, drCtrlVar: '', setDrCtrlVar: noop,
  drGroupVar: '', setDrGroupVar: noop,
  // extreme
  extValueVar: '', setExtValueVar: noop, extBlockSize: '10', setExtBlockSize: noop,
  extReturnPeriod: '100', setExtReturnPeriod: noop, extThreshold: '', setExtThreshold: noop,
  // mixture
  mixVars: [], setMixVars: noop, mixNComponents: '2', setMixNComponents: noop,
  mixThresh: '0', setMixThresh: noop,
  // GAM
  gamYVar: '', setGamYVar: noop, gamPredictors: [], setGamPredictors: noop,
  gamSmoothVars: [], setGamSmoothVars: noop, gamDf: '5', setGamDf: noop,
  gamFamily: 'gaussian', setGamFamily: noop,
  gamInteractVar1: '', setGamInteractVar1: noop, gamInteractVar2: '', setGamInteractVar2: noop,
  gamLambda: '0.1', setGamLambda: noop,
  // FDA
  fdaVars: [], setFdaVars: noop, fdaTimeVar: '', setFdaTimeVar: noop,
  fdaIdVar: '', setFdaIdVar: noop, fdaNBasis: '5', setFdaNBasis: noop,
  fdaNClusters: '2', setFdaNClusters: noop,
  // spatial
  spatCoordXVar: '', setSpatCoordXVar: noop, spatCoordYVar: '', setSpatCoordYVar: noop,
  spatValueVar: '', setSpatValueVar: noop, spatWeightType: 'inverseDistance', setSpatWeightType: noop,
  spatWeightThresh: '', setSpatWeightThresh: noop, spatWeightK: '5', setSpatWeightK: noop,
  spatNLags: '10', setSpatNLags: noop, spatNNeighbors: '10', setSpatNNeighbors: noop,
  spatPower: '2', setSpatPower: noop, spatNSim: '99', setSpatNSim: noop,
  spatRegPreds: [], setSpatRegPreds: noop, spatRegYVar: '', setSpatRegYVar: noop,
  spatXVars: [], setSpatXVars: noop, spatYVar: '', setSpatYVar: noop,
  spatIdVar: '', setSpatIdVar: noop, spatTimeVar: '', setSpatTimeVar: noop,
  spatHausBetaFe: '', setSpatHausBetaFe: noop, spatHausSeFe: '', setSpatHausSeFe: noop,
  spatHausBetaRe: '', setSpatHausBetaRe: noop, spatHausSeRe: '', setSpatHausSeRe: noop,
  spatStarP: '1', setSpatStarP: noop, spatStarQ: '1', setSpatStarQ: noop,
  spatForecastSteps: '3', setSpatForecastSteps: noop,
  // econometrics
  econYVar: '', setEconYVar: noop, econXVars: [], setEconXVars: noop,
  econY1Var: '', setEconY1Var: noop, econY2Var: '', setEconY2Var: noop,
  econYVars: [], setEconYVars: noop, econZVars: [], setEconZVars: noop,
  econSelectVar: '', setEconSelectVar: noop, econTreatVar: '', setEconTreatVar: noop,
  econOutcomeVar: '', setEconOutcomeVar: noop, econIdVar: '', setEconIdVar: noop,
  econTimeVar: '', setEconTimeVar: noop, econLowerBound: '0', setEconLowerBound: noop,
  econUpperBound: '', setEconUpperBound: noop, econMaxIter: '100', setEconMaxIter: noop,
  econBw: '', setEconBw: noop, econCaliper: '0.2', setEconCaliper: noop,
  econRatio: '1', setEconRatio: noop, econMaxLags: '2', setEconMaxLags: noop,
  econLags: '1', setEconLags: noop, econRank: '1', setEconRank: noop,
  econIdentification: 'chol', setEconIdentification: noop,
  econHausBetaFe: '', setEconHausBetaFe: noop, econHausSeFe: '', setEconHausSeFe: noop,
  econHausBetaRe: '', setEconHausBetaRe: noop, econHausSeRe: '', setEconHausSeRe: noop,
  // experimental + AB
  expBlockVar: '', setExpBlockVar: noop, expTreatVar: '', setExpTreatVar: noop,
  expRespVar: '', setExpRespVar: noop, expSubjectVar: '', setExpSubjectVar: noop,
  expBetweenVar: '', setExpBetweenVar: noop, expWithinVar: '', setExpWithinVar: noop,
  expPeriodVar: '', setExpPeriodVar: noop, expSequenceVar: '', setExpSequenceVar: noop,
  expPrimaryVar: '', setExpPrimaryVar: noop, expNestedVar: '', setExpNestedVar: noop,
  expNFactors: '3', setExpNFactors: noop, expNRuns: '10', setExpNRuns: noop,
  expEffectSize: '0.5', setExpEffectSize: noop, expAlpha: '0.05', setExpAlpha: noop,
  expCenterPts: '2', setExpCenterPts: noop, expNLevels: '3', setExpNLevels: noop,
  expModel: 'linear', setExpModel: noop, expSeed: '42', setExpSeed: noop,
  expD: '2', setExpD: noop, expN: '20', setExpN: noop,
  expEquivDL: '-0.5', setExpEquivDL: noop, expEquivDU: '0.5', setExpEquivDU: noop,
  expLengthScale: '1', setExpLengthScale: noop, expNoiseVar: '0.1', setExpNoiseVar: noop,
  expBestObserved: '0', setExpBestObserved: noop, expFactorsList: [], setExpFactorsList: noop,
  abExpectedRatio: '1', setAbExpectedRatio: noop, abAlpha: '0.05', setAbAlpha: noop,
  abBeta: '0.2', setAbBeta: noop, abBaseline: '0.5', setAbBaseline: noop,
  abMde: '0.1', setAbMde: noop, abSpending: 'obf', setAbSpending: noop,
  abNIter: '1000', setAbNIter: noop, abNArms: '3', setAbNArms: noop,
  // machine learning
  mlYVar: '', setMlYVar: noop, mlXVars: [], setMlXVars: noop,
  mlLambda: '0.1', setMlLambda: noop, mlAlpha: '0.5', setMlAlpha: noop,
  mlMaxIter: '200', setMlMaxIter: noop, mlTol: '1e-4', setMlTol: noop,
  mlC: '1.345', setMlC: noop, mlBandwidth: '0.5', setMlBandwidth: noop,
  mlDeg: '1', setMlDeg: noop, mlNTrees: '5', setMlNTrees: noop,
  mlMaxDepth: '5', setMlMaxDepth: noop, mlType: 'regression', setMlType: noop,
  mlSeed: '42', setMlSeed: noop, mlLearningRate: '0.1', setMlLearningRate: noop,
  mlLabels: '', setMlLabels: noop, mlNK: '5', setMlNK: noop,
  mlNSim: '100', setMlNSim: noop, mlFeatureI: '0', setMlFeatureI: noop,
  mlFeatureJ: '1', setMlFeatureJ: noop, mlBaseline: '', setMlBaseline: noop,
  mlNSamples: '20', setMlNSamples: noop, mlNGrid: '10', setMlNGrid: noop,
  // neural
  nnLogitsStr: '1,2,3,4', setNnLogitsStr: noop, nnTargetsStr: '0', setNnTargetsStr: noop,
  nnActInputStr: '-2,-1,0,1,2', setNnActInputStr: noop, nnActType: 'relu', setNnActType: noop,
  nnLr: '0.01', setNnLr: noop, nnEpochs: '50', setNnEpochs: noop,
  nnBatchSize: '', setNnBatchSize: noop, nnNHidden: '4', setNnNHidden: noop,
  nnSeed: '42', setNnSeed: noop, nnKernelStr: '0.5,0.5', setNnKernelStr: noop,
  nnStride: '1', setNnStride: noop, nnPadding: '0', setNnPadding: noop,
  nnPoolSize: '2', setNnPoolSize: noop, nnRate: '0.5', setNnRate: noop,
  nnEps: '1e-5', setNnEps: noop, nnNIn: '4', setNnNIn: noop, nnNOut: '6', setNnNOut: noop,
  nnBeta1: '0.9', setNnBeta1: noop, nnBeta2: '0.999', setNnBeta2: noop,
  nnParamsStr: '0.5,-0.3,0.8', setNnParamsStr: noop, nnGradsStr: '0.1,-0.2,0.05', setNnGradsStr: noop,
  nnMomStr: '0,0,0', setNnMomStr: noop, nnVelStr: '0,0,0', setNnVelStr: noop,
  // dim reduction
  dimVars: [], setDimVars: noop, dimPerplexity: '30', setDimPerplexity: noop,
  dimNComponents: '2', setDimNComponents: noop, dimMaxIter: '300', setDimMaxIter: noop,
  dimLr: '0.5', setDimLr: noop, dimSeed: '42', setDimSeed: noop,
  dimNNeighbors: '5', setDimNNeighbors: noop, dimMinDist: '0.1', setDimMinDist: noop,
  dimHiddenSize: '2', setDimHiddenSize: noop, dimLatentSize: '2', setDimLatentSize: noop,
  dimBeta: '0.5', setDimBeta: noop, dimDModel: '8', setDimDModel: noop,
  dimNHeads: '2', setDimNHeads: noop, dimDFF: '16', setDimDFF: noop,
  dimEpochsDL: '50', setDimEpochsDL: noop,
  dimAttentionQStr: '', setDimAttentionQStr: noop,
  dimAttentionKStr: '', setDimAttentionKStr: noop,
  dimAttentionVStr: '', setDimAttentionVStr: noop,
  // robust
  robSeed: '42', setRobSeed: noop, robAlpha: '0.75', setRobAlpha: noop,
  robH: '25', setRobH: noop, robBdp: '0.5', setRobBdp: noop,
  robA: '1.5', setRobA: noop, robB: '3', setRobB: noop, robC: '8', setRobC: noop,
  robNSim: '100', setRobNSim: noop,
  outlierK: '5', setOutlierK: noop, outlierNTrees: '50', setOutlierNTrees: noop,
  outlierSampleSize: '64', setOutlierSampleSize: noop,
  // bayesian
  bayesNIter: '0', setBayesNIter: noop, bayesNBurnin: '2000', setBayesNBurnin: noop,
  bayesPriorScale: '2.5', setBayesPriorScale: noop,
  bayesLogLik0: '-100', setBayesLogLik0: noop, bayesLogLik1: '-95', setBayesLogLik1: noop,
  bayesN: '50', setBayesN: noop, bayesK0: '2', setBayesK0: noop, bayesK1: '3', setBayesK1: noop,
  bayesS: '7', setBayesS: noop, bayesT: '20', setBayesT: noop,
  bayesPriorA: '1', setBayesPriorA: noop, bayesPriorB: '1', setBayesPriorB: noop,
  bayesPriorShape: '1', setBayesPriorShape: noop, bayesPriorRate: '1', setBayesPriorRate: noop,
  bayesPriorMean: '10', setBayesPriorMean: noop, bayesPriorSD: '5', setBayesPriorSD: noop,
  bayesKnownSigma: '2', setBayesKnownSigma: noop,
  bayesA0: '0.001', setBayesA0: noop, bayesB0: '0.001', setBayesB0: noop,
  bayesDicLogLik: '-100', setBayesDicLogLik: noop, bayesDicNParams: '5', setBayesDicNParams: noop,
  bayesBmaYVar: '', setBayesBmaYVar: noop, bayesBmaXVars: [], setBayesBmaXVars: noop,
  bayesBmaSeed: '42', setBayesBmaSeed: noop,
  // missing
  missVars: [], setMissVars: noop, missM: '5', setMissM: noop,
  missMaxIterMICE: '10', setMissMaxIterMICE: noop,
  missMaxIterEM: '100', setMissMaxIterEM: noop, missTolEM: '1e-5', setMissTolEM: noop,
  // signal
  sigValueVar: '', setSigValueVar: noop, sigValue2Var: '', setSigValue2Var: noop,
  sigWinSize: '64', setSigWinSize: noop, sigOverlap: '32', setSigOverlap: noop,
  sigSRate: '1', setSigSRate: noop, sigNLags: '20', setSigNLags: noop,
  // SEM
  semVars: [], setSemVars: noop, semEquations: 'f1 =~ x1 + x2 + x3', setSemEquations: noop,
  semTimes: '0,1,2,3', setSemTimes: noop, semGfactor: '', setSemGfactor: noop,
  semGroupFactors: [], setSemGroupFactors: noop, semGroupVar: '', setSemGroupVar: noop,
  // text
  textDocs: 'the quick brown fox', setTextDocs: noop, textInput: 'hello world', setTextInput: noop,
  textNTopics: '3', setTextNTopics: noop, textNGram: '2', setTextNGram: noop,
  textQuery: 'machine learning', setTextQuery: noop, textVecSize: '10', setTextVecSize: noop,
  textWindow: '2', setTextWindow: noop,
  // survey
  svyWeights: '1,1,1,1,1', setSvyWeights: noop, svyP: '0.5', setSvyP: noop,
  svyTargets: '10,10', setSvyTargets: noop, svyAuxVars: '1,1,1', setSvyAuxVars: noop,
  svyPopTotals: 'yes:30,no:20', setSvyPopTotals: noop, svyStrataVar: '', setSvyStrataVar: noop,
  // copula
  copulaVars: [], setCopulaVars: noop, copulaFamily: 'gaussian', setCopulaFamily: noop,
  copulaTheta: '2', setCopulaTheta: noop, copulaNu: '4', setCopulaNu: noop,
  copulaSeed: '42', setCopulaSeed: noop,
};

describe('InferenceConfig', () => {
  test('renders without crashing', () => {
    const { container } = render(
      <InferenceConfig active="t_welch" ds={mockDs} data={[]} state={mockState} set={noop} />
    );
    expect(container.firstChild).toBeTruthy();
  });
});
