#!/usr/bin/env node
// Generates the namespaced public API barrel (packages/statlab/src/index.js)
// and the per-module `exports` map in packages/statlab/package.json.
//
// Namespacing (one namespace per module) resolves the cross-module function-name
// collisions, so no `export *` flattening is attempted. Two modules share the
// basename `power` (math/power = low-level power primitives, methods/power =
// power-analysis methods); the barrel disambiguates the latter as `powerAnalysis`.
import { readdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, '..', 'packages', 'statlab');
const srcDir = join(pkgDir, 'src');

const isModule = (f) => f.endsWith('.js') && !f.endsWith('.test.js') && f !== 'index.js';
const listModules = (sub) =>
  readdirSync(join(srcDir, sub))
    .filter(isModule)
    .map((f) => f.replace(/\.js$/, ''))
    .sort();

const math = listModules('math');
const methods = listModules('methods');

// namespace disambiguation for duplicate basenames across dirs
const NS_OVERRIDE = { 'methods/power': 'powerAnalysis' };
const nsFor = (dir, name) => NS_OVERRIDE[`${dir}/${name}`] ?? name;

// sanity: no duplicate namespaces after overrides
const seen = new Map();
for (const [dir, names] of [['math', math], ['methods', methods]]) {
  for (const name of names) {
    const ns = nsFor(dir, name);
    if (seen.has(ns)) throw new Error(`namespace collision '${ns}': ${dir}/${name} vs ${seen.get(ns)}`);
    seen.set(ns, `${dir}/${name}`);
  }
}

// --- barrel ---
const lines = ['// AUTO-GENERATED by scripts/gen-barrel.mjs — do not edit by hand.', ''];
lines.push('// math primitives');
for (const name of math) lines.push(`export * as ${nsFor('math', name)} from './math/${name}.js';`);
lines.push('', '// statistical methods');
for (const name of methods) lines.push(`export * as ${nsFor('methods', name)} from './methods/${name}.js';`);
lines.push('');
writeFileSync(join(srcDir, 'index.js'), lines.join('\n'));

// --- exports map ---
const exportsMap = {
  '.': { types: './dist/index.d.ts', import: './src/index.js', require: './dist/index.cjs' },
};
const addSub = (dir, name) => {
  exportsMap[`./${dir}/${name}`] = {
    types: `./dist/${dir}/${name}.d.ts`,
    import: `./src/${dir}/${name}.js`,
    require: `./dist/${dir}/${name}.cjs`,
  };
};
for (const name of math) addSub('math', name);
for (const name of methods) addSub('methods', name);
exportsMap['./package.json'] = './package.json';

const pkgPath = join(pkgDir, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
pkg.exports = exportsMap;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

console.log(`barrel: ${math.length} math + ${methods.length} methods = ${math.length + methods.length} namespaces`);
console.log(`exports: ${Object.keys(exportsMap).length} entries`);
